name: Deploy to GitHubPages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy with gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: editor
